### ISSUE TITLE
Game is not starting - User interaction need to be implemented

### ISSUE THREAD

**Issue by di-press** [courselab/snaskii21#10]
Hello there!

This issue was created to superimpose the issue #4. In issue #4, was discovered that the problem is not WSL itself, but the absence of user interaction handling - the only implemented functionality is when the user presses the 'q' key, to exit the game - but other keys are not being handled, giving the impression that the problem could be related to WSL.

Since the code to handle user interaction is not implemented yet, it is an opportunity to us, guys! :)

**Comment by Float07** [comment]
I think this issue should be labeled as critical, since it's the essential for the project to run. I'll add the label but feel free to remove if you don't think it's appropriate ;)

**Comment by monacofj** [comment]
Folks, the idea of this exercise is to extend the implementation of an incomplete piece of software.
Perhaps 'bug' would more properly refer to code that already exists; for now, we rather have just ongoing development... I guess.

**Comment by artP2** [comment]
I think it was fixed, at least partially, by PR #74.

**Comment by CarlosCraveiro** [comment]
I agree with @artP2, I think it was fixed too. Now we have an already playable game at the develop branch!! PR #95, PR #93, PR #87, PR #74 and so on...

**Comment by artP2** [comment]
Since the game is running acceptably, I'm closing this issue.
