### ISSUE TITLE
🆕 Feature issue - Implement score saving and high-score screen

### ISSUE THREAD

**Issue by LSatoshi** [courselab/snaskii21#112]
Implement a score saving system that allow the player to save their score and initials, just like in old arcade games, and a high-score menu that shows up the best scores after each game

**Comment by gabriel-vr** [comment]
The instructions are not shown at the bottom of the game end screen. Do you think it would be a good idea to show the scores in this part of the screen? 
![Captura de tela de 2021-12-01 16-07-51](https://user-images.githubusercontent.com/66570705/144298381-d7d103e2-ea25-4555-90cb-4c9cf595508a.png)

I think it would be nice to display the scores there and display a input area under "Press 'r' to play again!" where the user could insert their initials and save the score if he wants so.

**Comment by LSatoshi** [comment]
I think it would be a great idea! There's a lot of empty space there and we don't need to add a new screen

**Comment by CaioRib** [comment]
Your ideia is to save locally the top scores from the instance game installed on the player's pc, right? I think it's kinda hard to make a global top-score without using any server structure.

**Comment by gabriel-vr** [comment]
Yeah i intend to implement a local score system.
