### ISSUE TITLE
"develop" branch is not protected

### ISSUE THREAD

**Issue by Float07** [courselab/snaskii21#12]
I noticed that the _develop_ branch is not protected, meaning collaborators can push directly to it. I'd recommend we add a "Require pull request reviews before merging" rule (take a look [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging)), which would make so that any change to _develop_ could only be made through pull requests approved by a set amount of reviewers with write access.
This would avoid people from accidentally pushing directly to _develop_ and would encourage collaborators to review PRs.

I know this won't involve changes in the repo's files so sorry if this shouldn't be made into an issue.

**Comment by Float07** [comment]
As far as I understand, we need someone with admin access to this repo to make this change, so I'll be adding @monacofj to this issue

**Comment by jufantozzi** [comment]
Should we discuss a number of minimum approvals for unblocking merge? My guess is that this is something hard to guess at this point, since we dont know how many people will actually be interacting, which is maybe the most important factor? But if I were to guess, I'd say something around 3-4.

**Comment by jufantozzi** [comment]
But regardless of the chosen number, what I think it's crucial that we do, is evaluate over time how fast/slow are we merging things and if quality of code is increasing or decreasing. These should be the most relevant metrics when trying to pick the ideal number.

**Comment by Float07** [comment]
This can really be something hard to guess. Maybe now we should start with 2 (maybe 3), and if we notice that people are starting to get more active we can increase up to 4 (and maybe even more?).
And we should keep an eye on how things are going (speed and quality, as you said) after we set/change this number.

**Comment by monacofj** [comment]
Ok, let's start with some basic and then reevaluate eventually.
To start with, I configured `main` with 3 reviews, and `develop`  with 2, including the code owner if any.
Please, do not hesitate to reopen the issue should we discuss it further.
