### ISSUE TITLE
Missing Code of Conduct doc

### ISSUE THREAD

**Issue by Float07** [courselab/snaskii21#123]
## Describe the doc you think should be added or changed
Code of Conduct

## Additional context
We should add a code of conduct to the repo. its importance is stated [here](https://opensource.guide/code-of-conduct/).
Maybe it would help us to show how we support new contributors and help people engage.
What do you think? 

#

**Comment by math-araujo** [comment]
Nice idea! Do you have any suggestion of a specific code of conduct for us?

**Comment by Float07** [comment]
[this](https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md) is one of the main templates that shown up in my search. I liked the general structure of it, so maybe we could change some parts of it to use for ourself. 
We would need to change quite a bit I think, but it's a good starting point.

**Comment by Matezcp** [comment]
This template sounds good, maybe we could add something about USP and/or something about respect USP and any other universitys, schools and similars.

**Comment by Float07** [comment]
I unfortunately won't have the time to implement this change. Anyone please feel free to assign yourself to this Issue.
