### ISSUE TITLE
Help button is not implemented

### ISSUE THREAD

**Issue by viniciussm07** [courselab/snaskii21#127]
## Describe the bug
The `h` button is set to change the snake's direction, but there are instructions for it to be the help button.

## Steps to Reproduce
1. Run the game
2. While playing, press `h`

## What the expected behavior should've been
I see two options:
1. Remove the move `h`, `j`, `k`, `l` and implement the help button;
2. Set another help button.

## Relevant screenshots
![Screenshot from 2021-11-29 21-01-35](https://user-images.githubusercontent.com/78987625/143963854-7b7b5d9b-727d-4c7f-a38c-02532ff40331.jpg)

## Additional context
There is nothing in the code implementing the help button, just a print, line 264 snaskii21/src/ttsnake.c

#

**Comment by gabriel-vr** [comment]
What should the help button do? Display a screen that shows a set of instructions to play the game?

For me, the instructions needed by the user are already displayed.

**Comment by MauricioGGCatellan** [comment]
Maybe the button should show some text telling where to find help if the user is having trouble running the game (like, if they find a game breaking bug or something). It might cite this github or the readme file, for example.

**Comment by gabriel-vr** [comment]
What do you think it is better: use another key to show this screen or implement it using the "h"? 
For me, it would be simpler and more intuitive to use another key.

**Comment by Henrique1792** [comment]
Another suggestion is  use uppercased h - hjkl movement isn't a issue for gameplay; narrowing input option sounds inconvenient...

**Comment by viniciussm07** [comment]
I think putting these instructions when pausing the game would be more interesting...

**Comment by viniciussm07** [comment]
I think putting these instructions when pausing the game would be more interesting...

**Comment by viniciussm07** [comment]
> I think putting these instructions when pausing the game would be more interesting...

Implementing a menu on pause...
Adding something like:
  - Resume 'any key'
  - Help 'h'
  - Exit 'any key'

**Comment by heitormasson** [comment]
> > I think putting these instructions when pausing the game would be more interesting...
> 
> Implementing a menu on pause... Adding something like:
> 
>     * Resume 'any key'
> 
>     * Help 'h'
> 
>     * Exit 'any key'

I think the pause menu is a great idea and it should be submitted as an issue for a new feature, but I think choosing another key for help would be better as @gabriel-vr suggested.

Also, since it's not going to be available during the game, the 'h - help and settings' string should be removed from the bottom side of the screen to avoid confusion.
