### ISSUE TITLE
ttsnake.sh doesn't work depending on where you are calling it.

### ISSUE THREAD

**Issue by CarlosCraveiro** [courselab/snaskii21#128]
## Describe the bug
ttsnake.sh doesn't work depending on where you are calling it.
It happens because this script sometimes adds a parameter "-d scenes" to the ttsnake.bin executable which only makes sense to someone at the project's root directory.

## Steps to Reproduce
1. Go to another directory rather than the project's root directory and try to call ttsnake.sh
2. See the error.
3. If you don't see the error, try to modify one of the game scenes and see if it load the changes you made by trying again calling ttsnake.sh

## What the expected behavior should've been
A clear and concise description of what was expected to happen.

## Relevant screenshots
If applicable, add screenshots
![Peek 29-11-2021 21-43](https://user-images.githubusercontent.com/85318248/143965052-3f3fc912-bd6f-4387-b6e4-972b40ca7401.gif)

## Additional context
Just to clarify I'm using a distro Debian 11 - stable/bullseye.

#

**Comment by monacofj** [comment]
`ttsnake.sh` should not be called directly; it's just a provision for build-time testing.

This the explanation:

`ttsnake` binary reads scene files from the data install path (/usr/share) by default, unless called with `-d <scene-path>` option.
Therefore if one working in the project simple runs the binary, it will (inadvertently?) use the installed data scenes, and not the (possibly modified) project data scenes.

To avoid confusion, nside `src` there are three important files: 

- `ttsnake.bin`, the executable binary
- `ttsnake`, a script file that calls `ttsnake.bin` with '-d' option
- `ttsnake.sh` is just a template that Makefile uses to create `ttsnake`

When one runs `src/ttsnake`, one runs the script which calls the binary with the option to read the project, rather the the installed,  scenes.

When one issues `make install`, the binary `ttsnake.bin` is installed and renamed to `ttsnake`.

This is working properly. 

I don't see is a bug.
