### ISSUE TITLE
Pull request template 

### ISSUE THREAD

**Issue by Yudiaramos** [courselab/snaskii21#146]
## Describe the feature you think should be added
I was having a look at a couple of repositories and i've notice that some of them have a pull request template to help standardize the requests. The objective is to help the contributors to keep track on what's going on with a request, as well as making a more consistent workflow, making a better visual representation of what the pull request is about.

I saw we already got one, but I think we should add more information like on what I've put on additional context.

## Additional context
**I'm thinking about putting something like this:**

### Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

### Checklist
- [ ] I have tested this code
- [ ] I have updated the Readme

### Other comments

#

**Comment by joaofavoretti** [comment]
I think it's a really great idea to have that kind of template. It would really help code reviewers during pull request analysis.

Should we include that inside the CONTRIBUTING.md file?

**Comment by fernandovgs** [comment]
@joaofavoretti I think it would be better if we create a different file, like PULL_REQUEST_TEMPLATE.md. In my opinion, it is easier to find. What do you guys think?

**Comment by fernandovgs** [comment]
I checked better, and I found that a pull_request_template.md already exists. So we may just update this file.

**Comment by joaofavoretti** [comment]
Yeah! If you manage to change its name to PULL_REQUEST_TEMPLATE.md (using uppercases) to make it similary to the CONTRIBUTING.md or README.md as well.
What do you think about that? @fernandovgs

**Comment by joaofavoretti** [comment]
Do not forget to mention about that file template during the steps of contribution inside CONTRIBUTING.md file.

I liked checkboxes by the way

**Comment by fernandovgs** [comment]
> Yeah! If you manage to change its name to PULL_REQUEST_TEMPLATE.md (using uppercases) to make it similary to the CONTRIBUTING.md or README.md as well. What do you think about that? @fernandovgs

Good call! I will change its name to uppercase and mention it inside CONTRIBUTING.md in the current PR.
