### ISSUE TITLE
Elapsed time continues to count after pausing

### ISSUE THREAD

**Issue by viniciussm07** [courselab/snaskii21#148]
## Describe the bug
Elapsed time continues to count after pausing

## Steps to Reproduce
Pause the game while it is running

## What the expected behavior should've been
I think pausing elapsed time.

## Relevant screenshots
Look at the elapsed time.

![Elapsed Time](https://user-images.githubusercontent.com/78987625/145122047-8806ed4b-9fcf-4d2b-9ba5-bf83f6108648.gif)

**Comment by Haltz01** [comment]
I implemented this function and the time elapsed was not supposed to stop when the game is paused (so, inicially, it's not a bug), but if we all agree this is a bug, I believe it's simple to fix this. We just need to change a little bit the logic used to calculate and show the time elapsed.

**Comment by LeoFonsecaP** [comment]
> I implemented this function and the time elapsed was not supposed to stop when the game is paused (so, inicially, it's not a bug), but if we all agree this is a bug, I believe it's simple to fix this. We just need to change a little bit the logic used to calculate and show the time elapsed.

I think pausing the time makes sense is this scenario.

**Comment by JulioEO** [comment]
I agree that the time should be paused as well.
