### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by gabriel-libardi** [courselab/snaskii21#151]
I ran the game with valgrind (using the flag --leak-check=yes) and it detected memory leaks in two contexts: in the first one there were 14,400 bytes definitely lost in 1 block, and in the other one there  were 604,800 bytes definitely lost in 42 blocks. It also detected a possible memory leak in a third context, in which "272 bytes in 1 blocks are possibly lost", but I think this should not really be an issue.

Valgrind detected 1860 allocs, but only 1327 frees. The solution is to free the remaining allocated memory.

![memory](https://user-images.githubusercontent.com/93263761/145618254-e2ae254d-62a5-4417-a068-a35491b232ad.jpg)

**Comment by Haltz01** [comment]
I'm working on this problem right now. I've solved the pthread_create leak:
![pthread_create leak not here anymore](https://user-images.githubusercontent.com/47257437/148650445-ae6c77f5-df30-41e7-a372-f828e8492279.png)

Working on other leaks now. I'll create a `feature/#151` branch here.
