### ISSUE TITLE
Pull request template not present

### ISSUE THREAD

**Issue by Float07** [courselab/snaskii21#17]
Take a look [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for more info on pull request templates.
By adding a pull request template we would have one more way to enforce our workflow and avoid mistakes. What do you think?

We could discuss possible formats for our pull request template here. We can use the template to enforce that every pull request solves an issue and add a task list so it's clear what actions should be accomplished before making a PR, for example.

Additionally, maybe we should let someone who didn't collaborate yet to the project do this task? I think this should be easy (after we discuss what should the template look like) and a good place to start 😛

**Comment by andrecoco** [comment]
I can do this task. I think we should keep it simple, we can choose a default word (fix, resolve, ...) to link the PR to the issue it's fixing (this [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) explains it). 
And maybe a boilerplate to write what the PR changes.

Github shows the below example [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates):
![image](https://user-images.githubusercontent.com/16878985/141192319-f5c694e9-8f69-47ae-bf52-dcc48ff98be2.png)

**Comment by Float07** [comment]
Maybe keeping it simple is a good idea, so people don't get overwhelmed.

>Github shows the below example here:

I think it's a good idea to follow the example Github gives, this will enforce people to fix an issue with each PR and show changes in a summarized way.

**Comment by lucasvianav** [comment]
I like it. 

A template for issues would also be useful to help everyone raise more comprehensive issues with a good description of what the problem/suggestion is and any possible steps that may be taken to solve it, especially when involving the actual code. It should be a very similar (and easy) PR. I liked how #13 was formatted

**Comment by Float07** [comment]
>A template for issues would also be useful to help everyone raise more comprehensive issues with a good description

Good one! Wanna create an issue for that? Maybe we should also tag that as `easy` and let someone new take care of that (so we can get more people involved).

**Comment by lucasvianav** [comment]
> > A template for issues would also be useful to help everyone raise more comprehensive issues with a good description
> 
> Good one! Wanna create an issue for that? Maybe we should also tag that as `easy` and let someone new take care of that (so we can get more people involved).

Sure, will do

**Comment by andrecoco** [comment]
I think for the template to work it needs to be in one of these three places, according to [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).
- The root of the project
- .github folder
-  docs folder
 
 Should we rename the 'doc' folder to 'docs'?
