### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by LeoFonsecaP** [courselab/snaskii21#172]
## Describe the bug
Can´t open settings using 'h' in game or at the main menu. Can´t change maximum number of blocks to display at the same time. Also can´t change game speed.

## Steps to Reproduce
1. Run the game
2. Try to change settings at the main menu
3. Try to change settings mid game

## What the expected behavior should've been
Settings should be changed

**Comment by viniciussm07** [comment]
This issue is already being discussed in issue #127
