### ISSUE TITLE
No energy blocks being created

### ISSUE THREAD

**Issue by LeoFonsecaP** [courselab/snaskii21#173]
## Describe the bug
There are no energy blocks being generated, so the energy just runs out, impossible to progress

## Steps to Reproduce
1. Run the game
2. Play while you have energy
3. get no energy blocks

## What the expected behavior should've been
New energy blocks should appear.

## Relevant screenshots
![image](https://user-images.githubusercontent.com/63270818/146958158-66e060ed-160f-464d-9a10-ba67810e862e.png)

**Comment by yuji-teoi** [comment]
Strange. 
This happen once when I was changing some variables for my #170 pull request, but I fixed it in that time (if you see it and test it, and accept it, maybe this can fix this problem)

**Comment by yuji-teoi** [comment]
![image](https://user-images.githubusercontent.com/47069208/146973872-785f11cd-7529-421a-8f1a-4cc0cc3fe007.png)
It' something related to the position of the first energy block spawned. 
I changed it to [25][25] and it worked with my code on #170

**Comment by LeoFonsecaP** [comment]
> ![image](https://user-images.githubusercontent.com/47069208/146973872-785f11cd-7529-421a-8f1a-4cc0cc3fe007.png) It' something related to the position of the first energy block spawned. I changed it to [25][25] and it worked with my code on #170

How does it look in game? Can you screenshot it for me?

**Comment by yuji-teoi** [comment]
![image](https://user-images.githubusercontent.com/47069208/146974701-740bfc40-fb39-48ed-ba4d-91e1a3db44be.png)

**Comment by yuji-teoi** [comment]
My first guess is that the first position of the first energy block is not properly been assigned to the energy_block[0] variable.
There is a chance to fix the bug using the function that spawn a energy block on the screen instead of using the first position on the 'init_game' function. 
But the game loses the functionality for the game developer decide the first position of the energy block.

**Comment by LeoFonsecaP** [comment]
> My first guess is that the first position of the first energy block is not properly been assigned to the energy_block[0] variable. There is a chance to fix the bug using the function that spawn a energy block on the screen instead of using the first position on the 'init_game' function. But the game loses the functionality to the game developer decide the first position of the energy block.

I was able to fix it by putting the first energy block at the middle. I think its working, I´ll double check and push it.

**Comment by LeoFonsecaP** [comment]
I fixed the Energy problem, but I´m getting:
**double free or corruption (out)
Aborted (core dumped)**

when I close the game. Can you check if that´s happening with you as well or if my change broke it please @Tyago-Teoi

**Comment by yuji-teoi** [comment]
> I fixed the Energy problem, but I´m getting: **double free or corruption (out) Aborted (core dumped)**
> 
> when I close the game. Can you check if that´s happening with you as well or if my change broke it please @Tyago-Teoi

Have you opened a pull request ? Yep, I can check it

**Comment by LeoFonsecaP** [comment]
> > I fixed the Energy problem, but I´m getting: **double free or corruption (out) Aborted (core dumped)**
> > when I close the game. Can you check if that´s happening with you as well or if my change broke it please @Tyago-Teoi
> 
> Have you opened a pull request ? Yep, I can check it

I´ll do it now, I was trying to figure out how to fix the double free, but I´m not sure.
