### ISSUE TITLE
Double free 

### ISSUE THREAD

**Issue by LeoFonsecaP** [courselab/snaskii21#183]
## Describe the bug
When quitting the game, 
**double free or corruption (out)
Aborted (core dumped)**
error.

## Steps to Reproduce
1. Play the game
2. When you lose, quit at any time
3. See error

## What the expected behavior should've been
A clear and concise description of what was expected to happen.

## Relevant screenshots
![image](https://user-images.githubusercontent.com/63270818/146993921-27431f12-c1d1-421d-b369-66845a93b71e.png)

**Comment by Matezcp** [comment]
Maybe this issue is correlated with issue #151?

**Comment by Haltz01** [comment]
@LeoFonsecaP can you (or anyone available) try to reproduce this again? After the #258 fix, maybe this doesn't happen anymore. I wasn't able to cause the double free.

**Comment by LeoFonsecaP** [comment]
> @LeoFonsecaP can you (or anyone available) try to reproduce this again? After the #258 fix, maybe this doesn't happen anymore. I wasn't able to cause the double free.

I´m not getting double free anymore, but I´m still getting an error.
![image](https://user-images.githubusercontent.com/63270818/148807705-6f587ec3-9e1d-42b5-90ed-c5e1708d7df0.png)

Maybe we can close this issue and open a new one for the new error?

**Comment by Haltz01** [comment]
This other error is not related to memory leaks or corruption. It has to do with a feature introduced by someone related to sound (check lines with `ASSERT_SYSTEM_CALL`). Not all systems have the `mpg123` software by default (and sometimes they don't even have it available). So, this is just what you said: a different problem and maybe a new issue should be created to address it. 
I agree we can close this issue!

**Comment by lucasvianav** [comment]
I'll close this since it appears to have been solved by #258 and the remaining problem is not related to the original issue. Feel free to reopen it if the double free reappears
