### ISSUE TITLE
Add Barrier/Walls in the middle of the map

### ISSUE THREAD

**Issue by andrecoco** [courselab/snaskii21#189]
## Describe the feature you think should be added
I think the option to generate some barriers on the map that the snake can't touch is interesting, some variations of the game i found online have these obstacles.

## Relevant screenshots
![image](https://user-images.githubusercontent.com/16878985/147274360-b5f07f38-3a10-47c3-a82e-8789874112ff.png)

## Additional context
We can add a option to toggle this feature on/off.

#

**Comment by Float07** [comment]
I really liked this idea. Additionally we could add multiple difficulty levels for barriers generations, which would greatly increase replayability.

**Comment by yuji-teoi** [comment]
That's cool.

**Comment by cirofalsarella** [comment]
I checked the branch and it seems really cool, maybe check whether the walls are close to the snake at spawn

**Comment by andrecoco** [comment]
Good ideia, i will write some checks
