### ISSUE TITLE
Snake Spawning Faced to the Wall and Immediatly the Game is Over.

### ISSUE THREAD

**Issue by CaioRib** [courselab/snaskii21#191]
## Describe the bug
Sometimes when the game is started, the snake spawns faced to the borders, and the game is over before any player reaction.

## Steps to Reproduce
1. Start the game multiple times.
2. One of this times might happen what is being reported.

## What the expected behavior should've been
The snake must be faced to the further wall possible.

**Comment by allthecoder** [comment]
Strangely, I have tried to reproduce this and always the snake starts facing at the same point: from the left to the right. Can you record your screen or something like this to show the problem?

**Comment by yuji-teoi** [comment]
Very strange. The initial position of all elements of the game is fixed at the start of the playscene, as you can see in this 'init' function:
![image](https://user-images.githubusercontent.com/47069208/147477169-51ba2c92-8bc1-4771-8bb6-5d6ff0c8e59d.png)

But I had a problem related to initial position spawn with Energy Blocks (the '+' character of the game). The game just didn't spawned energy blocks, so I changed the initial position of the block and it worked. But days latter, changing nothing of the code and the same bug appear again ...

So this problem can be something more deep than we think ...

**Comment by CaioRib** [comment]
It happened yesterday after several restarts. I'll try to record the next executions to catch this behavior. I was running the master branch, so it wasn't related to any feature being developed. If I'm not able to reproduce again today, I will close this bug.

**Comment by CaioRib** [comment]
There it is. Maybe it's something related to the keyboard buffer, because it happens when I keep pressing keys on the menu.

The second time I press to play on this video this reported behavior happens.

https://user-images.githubusercontent.com/31256795/147511056-f6fbf2f1-ad5c-48aa-8e73-5d236c07761d.mp4

**Comment by CaioRib** [comment]
I've tested using Ubuntu and Windows Linux Subsystem, and on both if you press some random A,W,S,D on the menu this might happen.

**Comment by CaioRib** [comment]
I think a simple `fflush(stdin)` on `init_game()` could do the work.

**Comment by Haltz01** [comment]
I've added the `fflush()` to `init_game()` just as @CaioRib suggested. Can someone else check if the problem is fixed? Here, the game seems to run without this bug anymore.
