### ISSUE TITLE
Missing pipe of the border when the game starts

### ISSUE THREAD

**Issue by allthecoder** [courselab/snaskii21#193]
## Describe the bug
When the game starts, there is a | from the left that disappears. 

## Steps to Reproduce
1. Run the game.
2. Press 'p' to play.
3. See error.

## What the expected behavior should've been
The | needed to be in place. 

## Relevant screenshots
![missing pipe](https://user-images.githubusercontent.com/55332784/147469454-c8f5fc4e-eb20-418d-a275-d25c42ff35bc.png)

#

**Comment by yuji-teoi** [comment]
It's probably caused by the  body/tail of the snake that touches the border at the initial position of the snake.
I will see what I can do.
