### ISSUE TITLE
Sometimes the $ appears in the borders

### ISSUE THREAD

**Issue by allthecoder** [courselab/snaskii21#196]
## Describe the bug
Sometimes the $ appears in the borders, and this should not occur.

## Steps to Reproduce
1. Run the game.
2. Keep playing until the bug appears.
3. See error

## What the expected behavior should've been
The borders should only show | or -, ans sometimes the $ appears in the borders too. 

## Relevant screenshots
![image](https://user-images.githubusercontent.com/55332784/147477328-30503ff4-0973-4e73-b03c-69fbd579b473.png)

#

**Comment by yuji-teoi** [comment]
I will test some spawning limits here. 
Since I used the same function for generate '+' blocks to generate new '$', the bug could happen with the '+' too
