### ISSUE TITLE
Inform the user the key that allows him to skip the intro(during the intro) and change the key used to do that

### ISSUE THREAD

**Issue by FelipeMoleiro** [courselab/snaskii21#199]
## Describe the feature you think should be added
During the intro cutscene, there is no information that the user may skip the intro, and the only way to know this information is to read the controls in the documentation. I think it would be great if there was maybe a line under the cutscene informing it may be skipped.

Also the key used to skip the cutscene is 'q', which can be a problem, since it's the same one used to quit the game. The user may try to skip the cutscene and end up closing the application.

## Relevant screenshots

Normal Screen
![Screenshot from 2021-12-29 21-13-09](https://user-images.githubusercontent.com/40440420/147712112-79c250c0-f45b-41a1-975e-2c4c6540314a.png)

Proposed Solution(Write that the cutscene may be skipped with the chosen key, ie: 'q' or 'space')
![place](https://user-images.githubusercontent.com/40440420/147712273-79d65182-fdc3-4353-96b5-43bd93c5699e.png)

**Comment by CaioRib** [comment]
Nice addition, certainly improves the game usability, nicely done! I'll test later your feature branch before approve the pull request.
