### ISSUE TITLE
No one has been added to the authors' list on AUTHORS

### ISSUE THREAD

**Issue by Dauboau** [courselab/snaskii21#20]
I think it would be intuitive to add everyone who has asked to be a contributor to the authors' list.

**Comment by lucasvianav** [comment]
I think it'd be nice to add a script that populates that file using [GitHub's collaborators list](https://github.com/courselab/snaskii21/graphs/contributors)

**Comment by Dauboau** [comment]
@lucasvianav I have been looking for many ways to make that. The simplest is a python program (https://1drv.ms/u/s!Aru3Ae3ZrzQKoXROhWwdtie7Tjye?e=CVz9Bs) that prints every contributor based on the collaborators list and the we can just copy and paste it here in GitHub. However, there is a project (https://github.com/all-contributors/app) which can make a whole visual interface for the list that may be quite interesting using an interactive bot or a node java script. Anyway, I could not find a fully automatic way to fill the document without some level of manual labour(Maybe I just know too little about js). What do you all think? May we use the bot?

**Comment by lucasvianav** [comment]
Hey @Dauboau, I think our best bet to fully automate this is using [GitHub Actions](https://github.com/features/actions). After a quick search I came across [this one](https://github.com/marketplace/actions/contribute-list) that seems to be up for the job and is quite easy to set up. What do you think about it?

>The simplest is a python program (https://1drv.ms/u/s!Aru3Ae3ZrzQKoXROhWwdtie7Tjye?e=CVz9Bs) that prints every contributor based on the collaborators list and the we can just copy and paste it here in GitHub.

As a side note, it's probably not safe to expose a GH token in a public repo, it'd be better to revoke it (don't know if that is your actual token, but thought it'd worth mentioning)

**Comment by Dauboau** [comment]
Yes, that's the one I came across when I deleted my comment kkkkk. I am doing some tests and agree that it seems a great option. And thanks about the token, it is temporary, but I think you are right.

> Hey @Dauboau, I think our best bet to fully automate this is using [GitHub Actions](https://github.com/features/actions). After a quick search I came across [this one](https://github.com/marketplace/actions/contribute-list) that seems to be up for the job and is quite easy to set up. What do you think about it?
> 
> > The simplest is a python program (https://1drv.ms/u/s!Aru3Ae3ZrzQKoXROhWwdtie7Tjye?e=CVz9Bs) that prints every contributor based on the collaborators list and the we can just copy and paste it here in GitHub.
> 
> As a side note, it's probably not safe to expose a GH token in a public repo, it'd be better to revoke it (don't know if that is your actual token, but thought it'd worth mentioning)
