### ISSUE TITLE
Missing template for issues

### ISSUE THREAD

**Issue by lucasvianav** [courselab/snaskii21#22]
In addition to #17, a template for issues would also be useful to help everyone raise more comprehensive issues with a good description of what the problem/suggestion is and any possible steps that may be taken to solve it, especially when involving the actual code. 

It should be a very similar (and easy) PR to #17's. Suggestion: I liked how #13 was formatted.

Feel free to discuss about it here :)

_Originally posted by @lucasvianav in https://github.com/courselab/snaskii21/issues/17#issuecomment-965804067_

**Comment by LeoFonsecaP** [comment]
I like the idea of having a template, but I feel like the one on #13 might be too much for smaller issues. Maybe we can have two different templates, one for bigger issues and one for smaller ones.

**Comment by Float07** [comment]
I'll also side with a simpler template (like #17 is planning to do with PR template) or one simple and one more complex, so people can pick one.

**Comment by lucasvianav** [comment]
I think it'd be cool to provide the two templates (if GitHub has support for it), but am fine either way

**Comment by Yudiaramos** [comment]
Hey guys, I had some ideas on issues templates, you think I could take a crack at recreating something like this?
![example-template](https://user-images.githubusercontent.com/71808184/143094262-daaf9820-d106-469b-aa15-6aec7518988b.png)

I would obviously be adding the various issues we have, like the "+critical" or "feature" reports. We could also add some guidelines to making these reports like the one on #13 in the long run...

**Comment by Yudiaramos** [comment]
I just made a PR #107 for the issue, can somebody check it, please?

**Comment by lucasvianav** [comment]
> I just made a PR #107 for the issue, can somebody check it, please?

I'll take a look at it as soon as I can if it's not merged till then :)
