### ISSUE TITLE
Add a game speed numeric display

### ISSUE THREAD

**Issue by heitormasson** [courselab/snaskii21#228]
## Describe the feature you think should be added
Currently, you can change the game speed through +/- keys. However, it is only possible to confirm it was effective when watching the snake movement. It is hard to determine before that if the chosen speed is reasonable and to get back to the default after changing it.

It would be a good addition to insert a numeric scale to the game speed (0 to 10, 5 being the default, for instance) and display it as it is done with the score and energy variables. 

## Relevant screenshots
![image](https://user-images.githubusercontent.com/31258296/148459148-fbe09e89-df7e-4388-830b-6e285bef45b7.png)

An example of how it could look

#

**Comment by yuji-teoi** [comment]
Good idea.
