### ISSUE TITLE
Song does not play when game is executed outside repository folder

### ISSUE THREAD

**Issue by Idalen** [courselab/snaskii21#237]
## Describe the bug
Song does not play when game is executed outside repository folder. Only when you call `ttsnake` in snaskii21 folder it plays.

## Steps to Reproduce
1. Execute game in repository folder
2. Then execute it in any other folder

## What the expected behavior should've been
The song should be reproduced whatever the directory you execute the binary.

#

**Comment by l-a-motta** [comment]
Would it be possible to either remove the specific path here...
`system("mpg123 --no-visual --no-control --quiet ./sound/maintheme.mp3 &");`

And turn it into...
`system("mpg123 --no-visual --no-control --quiet sound/maintheme.mp3 &");`

Or use a different setting for mpg123 and simply reference a song using a URL? More about it [over here](https://www.mankier.com/1/mpg123), in the section about HTTP support

**Comment by l-a-motta** [comment]
I created a branch for this issue, fix-audio-filepath-error

**Comment by l-a-motta** [comment]
Fixed with PR #244
