### ISSUE TITLE
Continuation: loose files and duplicates

### ISSUE THREAD

**Issue by l-a-motta** [courselab/snaskii21#243]
This is a continuation from issue #217. Created so discussion can be better segmented.

**Comment by lucasvianav** [comment]
So this issue proposes to delete the "README" file?

**Comment by l-a-motta** [comment]
> So this issue proposes to delete the "README" file?

I don't know the purpose of the 0 byte README file, so that's what was proposed. Unless someone has a reason to keep it, then it would be good to have it explained here at least

**Comment by lucasvianav** [comment]
Yeah, makes sense to me. @APMedrado wanna take this one?

**Comment by APMedrado** [comment]
Sure! I'll do it shortly.

**Comment by lucasvianav** [comment]
Closed by #336
