### ISSUE TITLE
Renaming 'doc' folder to 'docs'

### ISSUE THREAD

**Issue by andrecoco** [courselab/snaskii21#25]
On issue #17 for the pull request template to work, it needs to be on 'docs' folder, not 'doc'.
I think renaming it would also makes the CONTRIBUTING.md show up on the Community tab on "Insights", according to [this](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) page.

**Comment by Float07** [comment]
Seems like a good idea. I think we should stick to Github's standard and rename "doc" to "docs" (also changing the location of CONTRIBUTING.md).

**Comment by lucasvianav** [comment]
Just remember to update any files with reference to documents inside that. e.g.: the README.md has a link to CONTRIBUTING.md
