### ISSUE TITLE
Time elapsed with problem again (someone ignored the fix!)

### ISSUE THREAD

**Issue by Haltz01** [courselab/snaskii21#264]
## Description
#221 fixed the problem with the time elapsed when the game was paused. This fix paused the timer when the game was paused. However, the `develop` branch doesn't have this change anymore. This means that someone made a mistake while accepting PRs and the problem returned.

## Steps to Reproduce
1. Go to #221 and see the changes that were made
2. Go to the `develop` branch
3. Check the `void showscene()` function
4. Compare both codes (the changes were unmade)

## What should happen?
Time elapsed should be paused when the game is paused.

## Relevant screenshots
Changes made in #221:
![image](https://user-images.githubusercontent.com/47257437/148655957-b8345416-5274-45aa-be73-b5275630b98a.png)

Current code status:
![image](https://user-images.githubusercontent.com/47257437/148655994-28681ac4-b336-4a8f-9baa-973eca25670e.png)

@Tyago-Teoi can you do the changes you did to time elapsed one more time? Otherwise, I could replicate what you did in #221 ...

**Comment by marcuscastelo** [comment]
I've analyzed the file history. Not sure what happened but I think maybe on #225 merging, the old lines were chosen by mistake.

![code-diff image](https://user-images.githubusercontent.com/27441558/148656283-d34ccfbf-397f-4af0-a0ed-919a1470c3b7.png)

[Code diff on github](https://github.com/courselab/snaskii21/commit/6551b2229ad6050db1c8437c8058d9cd7ff4598c#diff-9f8bdd20a3a03993bf90009974db3eca6b2430bbd47da992acaa02117c44f067L286-L293)

**Comment by yuji-teoi** [comment]
:( finally an error appeared in the project.
I can solve this.
