### ISSUE TITLE
Remove initial '$' from commands on README.md

### ISSUE THREAD

**Issue by guijun13** [courselab/snaskii21#284]
There's no need for the '$' before the command, such as:
``` bash
$ sudo apt install automake autoconf
```
because it can cause "command not found" error mostly for someone who is new to terminal commands, as they probably would copy the whole line or use the copy button from Github (when mouse hovering the code block):
![github_copy_command](https://user-images.githubusercontent.com/48109548/149154777-a52e6968-6bda-4471-a181-d018519d949d.png)

**Comment by joaofavoretti** [comment]
I think that I agree with you on that. Even though I would not like to encourage that practice of copy and paste, it does not make sense to use the copy functionality if the text is not sth "pastable".

Some repositories that I have referenced do not use that "$" character indeed.
