### ISSUE TITLE
What is done by the "gui" folder?

### ISSUE THREAD

**Issue by joaofavoretti** [courselab/snaskii21#285]
Recently I was reading some of the outlier code within the project and I struggled to understand what is the "gui" folder all about.

I tried to remove it before compiling the executable and I was able to. The program worked just fine.

Is it part of code from an old fork or something like that? Or can I just remove it?

lmk If someone is able to give it a try.

**Comment by gpetrucci25** [comment]
It's a GUI version of the game. See here #47 and #48.
Take a look at the README inside the folder, it lists some dependencies, and then just run the makefile.
