### ISSUE TITLE
Standardize code blocks in README

### ISSUE THREAD

**Issue by lucasvianav** [courselab/snaskii21#333]
## Describe the doc you think should be added or changed
Whereas in most of the doc the correct code blocks are used (with three back-ticks: ```), at the end of the installation section there are some inline code blocks (with single back-ticks: `) that I think are out of place.

I think it'd be best to standardize it all to use three back-ticks.

Also, there are some `$` remaining from #284, so it's a good chance to remove them.

### Correct:
![image](https://user-images.githubusercontent.com/23108450/149545127-3c5a485e-db46-4ebd-8ac8-987bcae8aa97.png)

### Wrong:
![image](https://user-images.githubusercontent.com/23108450/149545358-92a91e09-0676-4da2-b5d9-94e25d9a6b34.png)

### Remaining `$`
![image](https://user-images.githubusercontent.com/23108450/149573603-3c09c5c4-8d2d-4eb2-98c0-953afe01fde7.png)

**Comment by leonrossi** [comment]
Good idea! However, does this fit with issue #284 as well? Because we wouldn't want to conflict due to the use of ```$``` before each command, which are already on some lines currently. We need to ensure that this is done correctly so that a new issue is not required.

**Comment by lucasvianav** [comment]
I don't think there will be a conflict since #284 was already closed. But I just noticed there are still some `$` in the README, so maybe those can be deleted here as well?
![image](https://user-images.githubusercontent.com/23108450/149572992-cc6164b7-650d-4f2c-8e28-6cc1e1f6958a.png)

**Comment by leonrossi** [comment]
I think it's better, because #284 was closed just after the ```$``` removes.

**Comment by lucasvianav** [comment]
I'll update the issue description

**Comment by APMedrado** [comment]
> Good idea! However, does this fit with issue #284 as well? Because we wouldn't want to conflict due to the use of `$` before each command, which are already on some lines currently. We need to ensure that this is done correctly so that a new issue is not required.

I'll be including this fix in the pull request!
