### ISSUE TITLE
Delete cold branches

### ISSUE THREAD

**Issue by lucasvianav** [courselab/snaskii21#335]
## Problem
We have **a lot** of cold branches open, whose PRs were already closed. I think we should delete those branches to keep the repository more organized. What do you think?

## Relevant screenshots
![image](https://user-images.githubusercontent.com/23108450/149555235-ed5f2da5-e1bf-4b81-b5ba-0b63ad269858.png)

**Comment by dbuzon** [comment]
Good idea. Should I delete all merged and closed branches?

**Comment by leonrossi** [comment]
Once the problem was solved with the branch created and the merge done in the main branch, I believe it can be deleted! It would be much more organized!

**Comment by lucasvianav** [comment]
> Good idea. Should I delete all merged and closed branches?

I say go for it!

**Comment by APMedrado** [comment]
Agreed. It would be great to keep a clean repository.

**Comment by APMedrado** [comment]
@dbuzon do you still need any help? Can we close this issue?

**Comment by dbuzon** [comment]
@APMedrado I deleted most of the branches that were closed, but there are still some that I'm not sure if I can delete. You can check them if you want and close the issue.
