### ISSUE TITLE
Can't quit during gameplay or when paused

### ISSUE THREAD

**Issue by gpetrucci25** [courselab/snaskii21#342]
## Description
Can't quit the game during the gameplay or when the game is paused.
The player is only able to quit when on the menu screen.

## Steps to reproduce
1. Start playing the game
2. Press 'q' during gameplay or after pressing 'p' to pause the game
3. Fail to quit the game

## Expected behavior 
The player should be able to quit the game at any time.

**Comment by Rafael-M-V** [comment]
Any idea where the bug might be?

**Comment by gpetrucci25** [comment]
The same thing happens when trying to restart. Can't be done pressing 'r' during gameplay or pause screen.

**Comment by gpetrucci25** [comment]
@Rafael-M-V Not yet.
