### ISSUE TITLE
Remove installation instructions from CONTRIBUTING.md

### ISSUE THREAD

**Issue by lucasvianav** [courselab/snaskii21#50]
I think it's redundant to have installation instructions in 3 different documents: INSTALL, README.md and CONTRIBUTING.md. It also makes updating the instructions harder (CONTRIBUTING.md is already outdated). 

It'd best to remove them from the contributing guidelines and only link the other ones instead.

**Comment by aocard** [comment]
I've removed the install instructions from CONTRIBUTING.md, as they were outdated and it didn't feel like the right place for them. Since INSTALL has more detailed install documentation than README.md, I've left them as they are but added a note about INSTALL inside README.

Leaving the issue open as there is still a note about the binary being a wrapper script, that I was not sure where to best place. For now, it is still in CONTRIBUTING.md.

**Comment by lucasvianav** [comment]
> I've removed the install instructions from CONTRIBUTING.md, as they were outdated and it didn't feel like the right place for them. Since INSTALL has more detailed install documentation than README.md, I've left them as they are but added a note about INSTALL inside README.
> 
> Leaving the issue open as there is still a note about the binary being a wrapper script, that I was not sure where to best place. For now, it is still in CONTRIBUTING.md.

What PR is that in?

**Comment by Float07** [comment]
> I've removed the install instructions from CONTRIBUTING.md, as they were outdated and it didn't feel like the right place for them.

These changes weren't made on `develop` branch and there's no PR with these changes pending. I think you are confused with something 😛. Read the [Contribution Guidelines](https://github.com/courselab/snaskii21/blob/develop/docs/CONTRIBUTING.md) and feel free to ask anything you have in mind :)

**Comment by aocard** [comment]
PR made (#60)

**Comment by lucasvianav** [comment]
> PR made (#60)

Hey @aocard

Before making a PR, it's good practice to check if there is already someone assigned to the issue you're trying to solve. If there isn't you can assign yourself, but if there is it's good to talk to those assigned and see if they're already working on it/are going to. 

In this particular case I wasn't able to start working on this issue yet, so it's fine, but for future reference the objective of this is to avoid multiple people doing the same changes more than once and to not waste anybody's work/respect it.

![image](https://user-images.githubusercontent.com/23108450/142092414-f2de796a-0cb8-4c62-ab25-c9db5702f595.png)

**Comment by Float07** [comment]
Hey I'll be closing this Issue since we had no update to the correspondent PR in a long time. But feel free to reopen!
