### ISSUE TITLE
Create a commit message convention to be used inside the project

### ISSUE THREAD

**Issue by joaofavoretti** [courselab/snaskii21#51]
Sometimes is useful to give a look at the commit history, mainly to check the last commits to each file. Therefore I propose a format to the commit messages, so that it improves not only the approach to the commit history but also the approach on pull request commits.
The result is pretty simple, reading the commit message should explain what was done in terms of code.

So I propose that on each commit message, we following format:

```
"<type>(<scope>): <short summary>"
   │       │             │
   │       │             └─> Summary in present tense. Not capitalized. No period at the end.
   │       │
   │       └─> Commit Scope: animations|common|compile|core|elements|forms|language-service|
   |                           platform|dynamic|platform-server|upgrade|packaging
   │
   └─> Commit Type: build|docs|feat|fix|perf|refactor|test
```
(Sure that "type" and "scope" keywords can be discussed)

In that way, we can reduce the amount of modifications per commit (seems that the short summary must involve the modifications in general) and spare the necessity of reading the whole code diff in order to understand the commit.

Of course that just using the short summary should be enough in some of the times, but it proposes a way so that it is standardized.

**Comment by Float07** [comment]
I think it can be a good idea to standardize the commit messages, but (at least for me, who is kinda naive with these terms) the `type` and `scope` keywords seem a little too technical. At least it looks like to me that it would be some extra work to some people with less experience. Maybe these keywords could be replaced by something simpler, like the tags we are using for the issues?

Just my view on this though, maybe getting the view of someone with more experience can be relevant.

**Comment by joaofavoretti** [comment]
Oh yeah, I guess that using labels might be a good idea indeed.
