### ISSUE TITLE
Make snake's movement

### ISSUE THREAD

**Issue by pedgrando** [courselab/snaskii21#73]
Apart from initializing the game itself, the next step is to start working on the function that performs the snake's movement and assigns the WASD keys to its respective movements.

**Comment by Float07** [comment]
I think this is issue #10 . Feel free to reopen this issue if you think I'm wrong.

**Comment by pedgrando** [comment]
> I think this is issue #10 . Feel free to reopen this issue if you think I'm wrong.

You're right, this was part of issue #10. But, in the meantime, I realized that there's a bug in the snake's movement: it is allowed to crawl over itself. Should I report it in another issue or should I just edit this one, since it didn't have a purpose ?

**Comment by Float07** [comment]
I think the correct procedure is to create a new one, sice for a new person reading the comments it can be a little confusing to interpret the changing of purpose of this issue.
